version: '2'

services:
  app:
    image: 'cooperative-voting:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: 'mongo'
    container_name: db
    volumes:
      - "mongobdata:/data/db"
  redis:
    image: "redis:latest"
    container_name: "redis"
volumes:
  mongobdata: